version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build"
          command: docker build -t filebrowser/builder:latest .
  release:
    docker:
        - image: circleci/buildpack-deps
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Docker login
            command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - run:
            name: Docker build
            command: docker build -t filebrowser/builder:latest -t filebrowser/builder:${CIRCLE_TAG} .
        - run:
            name: Docker push
            command: |  
              docker push filebrowser/builder:latest
              docker push filebrowser/builder:${CIRCLE_TAG}
        - run: docker logout
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          context: deploy
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/